import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Terms of Service - BananaFood',
  description: 'Terms of Service for BananaFood',
};

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-amber-50 to-amber-100 p-6">
      <div className="max-w-3xl mx-auto bg-white/80 backdrop-blur-lg rounded-2xl shadow-xl p-8 md:p-12">
        <h1 className="text-3xl font-bold text-zinc-900 mb-2">Terms of Service</h1>
        <p className="text-sm text-zinc-500 mb-8">Last updated: {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</p>

        <div className="prose prose-sm max-w-none text-zinc-700 space-y-6">
          <section>
            <h2 className="text-xl font-semibold text-zinc-900 mt-6 mb-3">1. Acceptance of Terms</h2>
            <p>By accessing and using BananaFood, you accept and agree to be bound by the terms and provision of this agreement. If you do not agree to these terms, please do not use our service.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-zinc-900 mt-6 mb-3">2. Service Description</h2>
            <p>BananaFood provides AI-powered menu translation and food recognition services. We use artificial intelligence technology to process images you upload and provide translation or recognition results.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-zinc-900 mt-6 mb-3">3. User Accounts</h2>
            <p>To use our service, you must create an account through our authentication provider (Clerk). You are responsible for:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Maintaining the confidentiality of your account credentials</li>
              <li>All activities that occur under your account</li>
              <li>Notifying us immediately of any unauthorized use of your account</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-zinc-900 mt-6 mb-3">4. Acceptable Use</h2>
            <p>You agree to use our service only for lawful purposes and in accordance with these Terms. You agree not to:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Upload any content that is illegal, harmful, threatening, abusive, or violates any rights of others</li>
              <li>Use the service to transmit any malicious code or viruses</li>
              <li>Attempt to gain unauthorized access to our systems or interfere with the service</li>
              <li>Use automated scripts or bots to abuse the service</li>
              <li>Reverse engineer or attempt to extract the source code of our service</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-zinc-900 mt-6 mb-3">5. Intellectual Property</h2>
            <p>The images you upload remain your property. The processed results generated by our service are also your property. However, the BananaFood service itself, including all software, designs, and content, is the property of BananaFood and is protected by intellectual property laws.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-zinc-900 mt-6 mb-3">6. Service Availability</h2>
            <p>We strive to provide reliable service, but we do not guarantee that our service will be available 100% of the time. The service may be unavailable due to:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Scheduled maintenance</li>
              <li>Technical issues or failures</li>
              <li>Third-party service outages</li>
              <li>Force majeure events</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-zinc-900 mt-6 mb-3">7. Limitation of Liability</h2>
            <p>Our service uses AI technology, and we do not guarantee the accuracy of translation or recognition results. You acknowledge that:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li>AI-generated results may contain errors or inaccuracies</li>
              <li>You should verify important information independently</li>
              <li>We are not liable for any decisions made based on our service results</li>
              <li>We are not responsible for any losses or damages arising from the use of our service</li>
              <li>We are not responsible for issues with third-party services (Clerk, Google Gemini, Vercel)</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-zinc-900 mt-6 mb-3">8. Service Modifications</h2>
            <p>We reserve the right to modify, suspend, or discontinue any aspect of our service at any time, with or without notice. We are not liable to you or any third party for any modification, suspension, or discontinuation of the service.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-zinc-900 mt-6 mb-3">9. Termination</h2>
            <p>You may stop using our service at any time by deleting your account. We reserve the right to suspend or terminate your access to the service if you violate these Terms.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-zinc-900 mt-6 mb-3">10. Changes to Terms</h2>
            <p>We may update these Terms of Service from time to time. We will notify you of any changes by posting the new Terms on this page and updating the "Last updated" date. Your continued use of the service after such changes constitutes acceptance of the new Terms.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-zinc-900 mt-6 mb-3">11. Contact Us</h2>
            <p>If you have any questions about these Terms of Service, please contact us at <a href="mailto:nextbigtoy@gmail.com" className="text-blue-600 hover:underline">nextbigtoy@gmail.com</a>.</p>
          </section>
        </div>

        <div className="mt-8 pt-6 border-t border-zinc-200">
          <Link 
            href="/" 
            className="text-blue-600 hover:underline text-sm"
          >
            ← Back to Home
          </Link>
        </div>
      </div>
    </div>
  );
}
